#!/bin/sh
set -e
ripper-tags -R

# Using ripper-tags for now (it seems better for ruby), but could go back to
# ctags-exuberant in the future.
#
#PATH="/usr/local/bin:$PATH"
#trap 'rm -f "$$.tags"' EXIT
#git ls-files | \
#  ctags --tag-relative -L - -f"$$.tags" --languages=-javascript,sql,ruby
#mv "$$.tags" "tags"
