#!/bin/sh

# Running some commands to prep the project before launching tmux
cd ~/Development/personal/maggiesmarvels.com

# Setup and run function to setup new tmux session
function load_session() {
  local SESSION=maggiesmarvels

  if ! tmux has-session -t $SESSION; then
    tmux new-session -s $SESSION -n vim -d
    tmux new-window -n shell -t $SESSION
    tmux new-window -n foreman -t $SESSION
    tmux new-window -n logs -t $SESSION

    tmux split-window -t $SESSION:1 -p 15
    tmux split-window -t $SESSION:2 -v

    tmux send-keys -t $SESSION:1.1 'vim' C-m
    tmux send-keys -t $SESSION:1.2 'sleep 10 && foreman run bundle exec guard' C-m
    tmux send-keys -t $SESSION:2.1 'git pull && bundle install' C-m
    tmux send-keys -t $SESSION:3 'sleep 10 && foreman start' C-m
    tmux send-keys -t $SESSION:4 'tail -f log/development.log' C-m

    tmux select-window -t $SESSION:1
    tmux select-pane -t $SESSION:1.1
  fi

  tmux attach -t $SESSION
}

load_session
