#!/bin/sh

# Running some commands to prep the project before launching tmux
cd ~/stripe/stripe-shopping

# Setup and run function to setup new tmux session
function load_session() {
  local SESSION=stripe-shopping

  if ! tmux has-session -t $SESSION; then
    tmux new-session -s $SESSION -n vim -d
    tmux new-window -n shell -t $SESSION
    tmux new-window -n grunt -t $SESSION
    tmux new-window -n server -t $SESSION
    tmux new-window -n mongo -t $SESSION

    tmux send-keys -t $SESSION:1 '$EDITOR' C-m
    tmux send-keys -t $SESSION:3 'grunt' C-m
    tmux send-keys -t $SESSION:4 'sleep 3 && bundle exec ruby bin/shopping_srv.rb' C-m
    tmux send-keys -t $SESSION:5 'mongod' C-m

    tmux select-window -t $SESSION:1
  fi

  tmux attach -t $SESSION
}
load_session
