#!/bin/sh

# Running some commands to prep the project before launching tmux
cd ~/stripe/pay-server

# Setup and run function to setup new tmux session
function load_session() {
  local SESSION=stripe-pay-server

  if ! tmux has-session -t $SESSION; then
    tmux new-session -s $SESSION -n vim -d
    tmux new-window -n zsh -t $SESSION
    tmux new-window -n rsync -t $SESSION
    tmux new-window -n devboxservices -t $SESSION
    tmux new-window -n localservices -t $SESSION

    tmux send-keys -t $SESSION:1 'vim' C-m
    tmux send-keys -t $SESSION:3 'scripts/bin/devbox.rb --skip-servs mine' C-m
    tmux send-keys -t $SESSION:4 'ssh qa-dev32' C-m
    tmux send-keys -t $SESSION:5 'scripts/bin/servers' C-m

    tmux select-window -t $SESSION:1
  fi

  tmux attach -t $SESSION
}
load_session
