#!/bin/sh

# Running some commands to prep the project before launching tmux
cd ~/Development/personal/tushiesandtantrums.com

# Setup and run function to setup new tmux session
function load_session() {
  local SESSION=tushiesandtantrums

  if ! tmux has-session -t $SESSION; then
    tmux new-session -s $SESSION -n vim -d
    tmux new-window -n zsh -t $SESSION
    tmux new-window -n foreman -t $SESSION
    tmux new-window -n guard -t $SESSION
    tmux new-window -n logs -t $SESSION
    tmux new-window -n console -t $SESSION

    tmux send-keys -t $SESSION:1 'vim' C-m
    tmux send-keys -t $SESSION:2 'git pull && bundle install' C-m
    tmux send-keys -t $SESSION:3 'sleep 10 && foreman start' C-m
    tmux send-keys -t $SESSION:4 'sleep 10 && foreman run bundle exec guard' C-m
    tmux send-keys -t $SESSION:5 'tail -f log/development.log' C-m
    tmux send-keys -t $SESSION:6 'sleep 10 && foreman run bundle exec rails console' C-m

    tmux select-window -t $SESSION:1
  fi

  tmux attach -t $SESSION
}
load_session
